Update doxygen settings

diff --git a/config/publish-doxygen b/config/publish-doxygen
--- a/config/publish-doxygen
+++ b/config/publish-doxygen
@@ -7,6 +7,36 @@ COMMIT_USER="Documentation Builder"
 COMMIT_EMAIL="travis@travis-ci.org"
 CHANGESET=$(git rev-parse --verify HEAD)
 
+#Doxygen
+DOXYGEN_VER=doxygen-1.8.12
+DOXYGEN_TAR=${DOXYGEN_VER}.linux.bin.tar.gz
+DOXYGEN_URL="http://ftp.stack.nl/pub/users/dimitri/${DOXYGEN_TAR}"
+DOXYGEN_BIN="/usr/local/bin/doxygen"
+
+skip() {
+	echo "$@" 1>&2
+	echo "Exiting..." 1>&2
+	exit 0
+}
+
+abort() {
+	echo "Error: $@" 1>&2
+	echo "Exiting..." 1>&2
+	exit 1
+}
+
+# check for pull-requests
+[ "${TRAVIS_PULL_REQUEST}" = "false" ] || \
+	skip "Not running Doxygen for pull-requests."
+
+# check for branch name
+[ "${TRAVIS_BRANCH}" = "master" ] || \
+	skip "Running Doxygen only for updates on 'master' branch (current: ${TRAVIS_BRANCH})."
+
+wget -O - "${DOXYGEN_URL}" | \
+		tar xz -C ${TMPDIR-/tmp} ${DOXYGEN_VER}/bin/doxygen
+    export PATH="${TMPDIR-/tmp}/${DOXYGEN_VER}/bin:$PATH"
+
 # Get a clean version of the HTML documentation repo.
 rm -rf ${HTML_PATH}
 mkdir -p ${HTML_PATH}
